#!/usr/bin/env bash

project_name=${1:?please enter the project name}

echo "将新建工程：$project_name"

[ -e ${project_name} ] && echo "工程名存在！" && exit -1

[ ! -d ${project_name} ] && mkdir -p ${project_name}


# generate a WHAT fly file.
touch ${project_name}/what.fl

# generate a AND perl file.
touch ${project_name}/and.sh

# generate a HOW project floder.
mkdir -p ${project_name}/how

exit

export WAH_ATOM='`'
export WAH_LINK='->'
export WAH_BEGIN='begin'
export WAH_END='end'
export WAH_CONFIG='config'
export WAH_ACTION='action'
export WAH_WHAT='what.fl'
export WAH_AND='and.pl'
export WAH_HOW='how'

