#!/usr/bin/env bash

project_name='default'

export WAH_ATOM='`'
export WAH_LINK='->'
export WAH_BEGIN='begin'
export WAH_END='end'
export WAH_CONFIG='config'
export WAH_ACTION='action'
export WAH_WHAT='what.fl'
export WAH_AND='and.pl'
export WAH_HOW='how'

[ ! -d ${project_name} ] && mkdir -p ${project_name}

cd ${project_name}

# generate a WHAT fly file.
[ ! -e ./what.fl ] && touch ./what.fl

# generate a AND perl file.
[ ! -e ./and.pl ] && touch ./and.pl

# generate a HOW project floder.
[ ! -d ./how ] && mkdir -p ./how

cd -
