# Auto-generated by tools/probe_models.py
AVAILABLE_MODELS = ["gemini-3-pro-preview", "gemini-3-flash-preview", "gemini-2.5-pro", "gemini-2.0-flash-exp"]

def get_best_heavy_model():
    for m in ["gemini-3-pro-preview", "gemini-2.5-pro"]:
        if m in AVAILABLE_MODELS: return m
    return AVAILABLE_MODELS[0] if AVAILABLE_MODELS else None

def get_best_fast_model():
    for m in ["gemini-3-flash-preview", "gemini-2.5-flash"]:
        if m in AVAILABLE_MODELS: return m
    return AVAILABLE_MODELS[0] if AVAILABLE_MODELS else None
